"""Health report builder for P6.6.1.

Generates:
  - 10_System/reports/health_report.json
  - 10_System/reports/health_report.md
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from scientra.environment.diagnostics import run_diagnostics
from scientra.environment.repair import generate_repair_suggestions


def _resolve_root() -> Path:
    from scientra.environment.checks import _resolve_root as _rr
    return _rr()

REPORTS_DIR = "10_System/reports"


def build_health_report_json(root: Path | None = None) -> Path:
    """Generate health_report.json. Returns output path."""
    if root is None:
        root = _resolve_root()

    diag = run_diagnostics(root)
    repair = generate_repair_suggestions(root)

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "health_score": diag["health_score"],
        "status": diag["status"],
        "summary": {
            "total_checks": diag["total_checks"],
            "passed": diag["passed"],
            "warnings": diag["warnings"],
            "failed": diag["failed"],
        },
        "checks": diag["checks"],
        "repair_suggestions": repair,
    }

    out_dir = root / REPORTS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "health_report.json"
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def build_health_report_md(root: Path | None = None) -> Path:
    """Generate health_report.md. Returns output path."""
    if root is None:
        root = _resolve_root()

    diag = run_diagnostics(root)
    repair = generate_repair_suggestions(root)

    score = diag["health_score"]
    status = diag["status"]
    icon = "🟢" if status == "healthy" else ("🟡" if status == "degraded" else "🔴")

    lines = [
        "# Scientra Copilot — System Health Report",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "",
        f"## Overall: {icon} {status.upper()} — Score: {score}/100",
        "",
        f"| Category | Count |",
        f"|----------|-------|",
        f"| ✅ Passed | {diag['passed']} |",
        f"| ⚠️ Warnings | {diag['warnings']} |",
        f"| ❌ Failed | {diag['failed']} |",
        f"| ℹ️ Info | {diag['info']} |",
        f"| **Total** | **{diag['total_checks']}** |",
        "",
        "## Check Results",
        "",
    ]

    for c in diag["checks"]:
        status_icon = {"PASS": "✅", "WARN": "⚠️", "FAIL": "❌", "INFO": "ℹ️"}.get(c.get("status", "INFO"), "❓")
        lines.append(f"### {status_icon} {c['name']}")
        lines.append(f"**Status:** {c['status']} | **Detail:** {c.get('detail', '')}")
        if c.get("fix"):
            lines.append(f"**Fix:** {c['fix']}")
        lines.append("")

    # Repair suggestions for non-PASS items
    if repair:
        lines.append("## Repair Suggestions")
        lines.append("")
        for s in repair:
            sev = "🔴" if s["severity"] == "FAIL" else "🟡"
            lines.append(f"### {sev} {s['problem']}")
            lines.append(f"**Cause:** {s.get('cause', 'Unknown')}")
            lines.append(f"**Fix:** {s['fix']}")
            lines.append("")

    lines.append(f"\n*Report auto-generated by Scientra Copilot P6.6.1*")
    lines.append("")

    out_dir = root / REPORTS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "health_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def build_all_health_reports(root: Path | None = None) -> dict[str, str]:
    """Generate both JSON and MD reports. Returns {name: relative_path}."""
    if root is None:
        root = _resolve_root()

    json_path = build_health_report_json(root)
    md_path = build_health_report_md(root)

    return {
        "health_report.json": str(json_path.relative_to(root)),
        "health_report.md": str(md_path.relative_to(root)),
    }
